server:
  port: 8080
spring:
  http:
    multipart:
      max-file-size: 250Mb
      max-request-size: 3000Mb
  application:
    name: monio-multipart
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

minio:
  endpoint: http://127.0.0.1:9100
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: share
  downloadUri: http://127.0.0.1:9101
  path: http://127.0.0.1:9100

swagger:
  enable: true